version: '3'
services:
  app:
    build: .
    container_name: my-app
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
